/* Copyright (C) 2011 Circuits At Home, LTD. All rights reserved.

This software may be distributed and modified under the terms of the GNU
General Public License version 2 (GPL2) as published by the Free Software
Foundation and appearing in the file GPL2.TXT included in the packaging of
this file. Please note that GPL2 Section 2[b] requires that all works based
on this software must also be made publicly available under the terms of
the GPL2 ("Copyleft").

Contact information
-------------------

Circuits At Home, LTD
Web      :  http://www.circuitsathome.com
e-mail   :  support@circuitsathome.com
*/

#ifndef HIDUSAGESTR_H_INCLUDED
#define HIDUSAGESTR_H_INCLUDED

const char pstrSpace							[] = " ";
const char pstrCRLF								[] = "\r\n";
const char pstrSingleTab						[] = "\t";
const char pstrDoubleTab						[] = "\t\t";
const char pstrTripleTab						[] = "\t\t\t";

// Usage Page String Titles
const char pstrUsagePageUndefined				[] = "Undef";
const char pstrUsagePageGenericDesktopControls	[] = "Gen Desktop Ctrls";
const char pstrUsagePageSimulationControls		[] = "Simu Ctrls";
const char pstrUsagePageVRControls				[] = "VR Ctrls";
const char pstrUsagePageSportControls			[] = "Sport Ctrls";
const char pstrUsagePageGameControls			[] = "Game Ctrls";
const char pstrUsagePageGenericDeviceControls	[] = "Gen Dev Ctrls";
const char pstrUsagePageKeyboardKeypad			[] = "Kbrd/Keypad";
const char pstrUsagePageLEDs					[] = "LEDs";
const char pstrUsagePageButton					[] = "Button";
const char pstrUsagePageOrdinal					[] = "Ordinal";
const char pstrUsagePageTelephone				[] = "Tel";
const char pstrUsagePageConsumer				[] = "Consumer";
const char pstrUsagePageDigitizer				[] = "Digitizer";
const char pstrUsagePagePID						[] = "PID";
const char pstrUsagePageUnicode					[] = "Unicode";
const char pstrUsagePageAlphaNumericDisplay		[] = "Alpha Num Disp";
const char pstrUsagePageMedicalInstruments		[] = "Medical Instr";
const char pstrUsagePageMonitor					[] = "Monitor";
const char pstrUsagePagePower					[] = "Power";
const char pstrUsagePageBarCodeScanner			[] = "Bar Code Scan";
const char pstrUsagePageScale					[] = "Scale";
const char pstrUsagePageMSRDevices				[] = "Magn Stripe Read Dev";
const char pstrUsagePagePointOfSale				[] = "POS";
const char pstrUsagePageCameraControl			[] = "Cam Ctrl";
const char pstrUsagePageArcade					[] = "Arcade";
const char pstrUsagePageReserved				[] = "Reserved";
const char pstrUsagePageVendorDefined			[] = "Vendor Def";

// Generic Desktop Controls Page
const char pstrUsagePointer						[] = "Pointer";
const char pstrUsageMouse						[] = "Mouse";
const char pstrUsageJoystick					[] = "Joystick";
const char pstrUsageGamePad						[] = "Game Pad";
const char pstrUsageKeyboard					[] = "Kbrd";
const char pstrUsageKeypad						[] = "Keypad";
const char pstrUsageMultiAxisController			[] = "Multi-axis Ctrl";
const char pstrUsageTabletPCSystemControls		[] = "Tablet PC Sys Ctrls";
const char pstrUsageX							[] = "X";
const char pstrUsageY							[] = "Y";
const char pstrUsageZ							[] = "Z";
const char pstrUsageRx							[] = "Rx";
const char pstrUsageRy							[] = "Ry";
const char pstrUsageRz							[] = "Rz";
const char pstrUsageSlider						[] = "Slider";
const char pstrUsageDial						[] = "Dial";
const char pstrUsageWheel						[] = "Wheel";
const char pstrUsageHatSwitch					[] = "Hat Switch";
const char pstrUsageCountedBuffer				[] = "Counted Buf";
const char pstrUsageByteCount					[] = "Byte Count";
const char pstrUsageMotionWakeup				[] = "Motion Wakeup";
const char pstrUsageStart						[] = "Start";
const char pstrUsageSelect						[] = "Sel";
const char pstrUsageVx							[] = "Vx";
const char pstrUsageVy							[] = "Vy";
const char pstrUsageVz							[] = "Vz";
const char pstrUsageVbrx						[] = "Vbrx";
const char pstrUsageVbry						[] = "Vbry";
const char pstrUsageVbrz						[] = "Vbrz";
const char pstrUsageVno							[] = "Vno";
const char pstrUsageFeatureNotification			[] = "Feature Notif";
const char pstrUsageResolutionMultiplier		[] = "Res Mult";
const char pstrUsageSystemControl				[] = "Sys Ctrl";
const char pstrUsageSystemPowerDown				[] = "Sys Pwr Down";
const char pstrUsageSystemSleep					[] = "Sys Sleep";
const char pstrUsageSystemWakeup				[] = "Sys Wakeup";
const char pstrUsageSystemContextMenu			[] = "Sys Context Menu";
const char pstrUsageSystemMainMenu				[] = "Sys Main Menu";
const char pstrUsageSystemAppMenu				[] = "Sys App Menu";
const char pstrUsageSystemMenuHelp				[] = "Sys Menu Help";
const char pstrUsageSystemMenuExit				[] = "Sys Menu Exit";
const char pstrUsageSystemMenuSelect			[] = "Sys Menu Select";
const char pstrUsageSystemMenuRight				[] = "Sys Menu Right";
const char pstrUsageSystemMenuLeft				[] = "Sys Menu Left";
const char pstrUsageSystemMenuUp				[] = "Sys Menu Up";
const char pstrUsageSystemMenuDown				[] = "Sys Menu Down";
const char pstrUsageSystemColdRestart			[] = "Sys Cold Restart";
const char pstrUsageSystemWarmRestart			[] = "Sys Warm Restart";
const char pstrUsageDPadUp						[] = "D-pad Up";
const char pstrUsageDPadDown					[] = "D-pad Down";
const char pstrUsageDPadRight					[] = "D-pad Right";
const char pstrUsageDPadLeft					[] = "D-pad Left";
const char pstrUsageSystemDock					[] = "Sys Dock";
const char pstrUsageSystemUndock				[] = "Sys Undock";
const char pstrUsageSystemSetup					[] = "Sys Setup";
const char pstrUsageSystemBreak					[] = "Sys Break";
const char pstrUsageSystemDebuggerBreak			[] = "Sys Dbg Brk";
const char pstrUsageApplicationBreak			[] = "App Break";
const char pstrUsageApplicationDebuggerBreak	[] = "App Dbg Brk";
const char pstrUsageSystemSpeakerMute			[] = "Sys Spk Mute";
const char pstrUsageSystemHibernate				[] = "Sys Hiber";
const char pstrUsageSystemDisplayInvert			[] = "Sys Disp Inv";
const char pstrUsageSystemDisplayInternal		[] = "Sys Disp Int";
const char pstrUsageSystemDisplayExternal		[] = "Sys Disp Ext";
const char pstrUsageSystemDisplayBoth			[] = "Sys Disp Both";
const char pstrUsageSystemDisplayDual			[] = "Sys Disp Dual";
const char pstrUsageSystemDisplayToggleIntExt	[] = "Sys Disp Tgl Int/Ext";
const char pstrUsageSystemDisplaySwapPriSec		[] = "Sys Disp Swap Pri/Sec";
const char pstrUsageSystemDisplayLCDAutoscale	[] = "Sys Disp LCD Autoscale";

// Simulation Controls Page
const char pstrUsageFlightSimulationDevice		[] = "Flight Simu Dev";
const char pstrUsageAutomobileSimulationDevice	[] = "Auto Simu Dev";
const char pstrUsageTankSimulationDevice		[] = "Tank Simu Dev";
const char pstrUsageSpaceshipSimulationDevice	[] = "Space Simu Dev";
const char pstrUsageSubmarineSimulationDevice	[] = "Subm Simu Dev";
const char pstrUsageSailingSimulationDevice		[] = "Sail Simu Dev";
const char pstrUsageMotocicleSimulationDevice	[] = "Moto Simu Dev";
const char pstrUsageSportsSimulationDevice		[] = "Sport Simu Dev";
const char pstrUsageAirplaneSimulationDevice	[] = "Airp Simu Dev";
const char pstrUsageHelicopterSimulationDevice	[] = "Heli Simu Dev";
const char pstrUsageMagicCarpetSimulationDevice	[] = "Magic Carpet Simu Dev";
const char pstrUsageBicycleSimulationDevice		[] = "Bike Simu Dev";
const char pstrUsageFlightControlStick			[] = "Flight Ctrl Stick";
const char pstrUsageFlightStick					[] = "Flight Stick";
const char pstrUsageCyclicControl				[] = "Cyclic Ctrl";
const char pstrUsageCyclicTrim					[] = "Cyclic Trim";
const char pstrUsageFlightYoke					[] = "Flight Yoke";
const char pstrUsageTrackControl				[] = "Track Ctrl";
const char pstrUsageAileron						[] = "Aileron";
const char pstrUsageAileronTrim					[] = "Aileron Trim";
const char pstrUsageAntiTorqueControl			[] = "Anti-Torque Ctrl";
const char pstrUsageAutopilotEnable				[] = "Autopilot Enable";
const char pstrUsageChaffRelease				[] = "Chaff Release";
const char pstrUsageCollectiveControl			[] = "Collective Ctrl";
const char pstrUsageDiveBrake					[] = "Dive Brake";
const char pstrUsageElectronicCountermeasures	[] = "El Countermeasures";
const char pstrUsageElevator					[] = "Elevator";
const char pstrUsageElevatorTrim				[] = "Elevator Trim";
const char pstrUsageRudder						[] = "Rudder";
const char pstrUsageThrottle					[] = "Throttle";
const char pstrUsageFlightCommunications		[] = "Flight Comm";
const char pstrUsageFlareRelease				[] = "Flare Release";
const char pstrUsageLandingGear					[] = "Landing Gear";
const char pstrUsageToeBrake					[] = "Toe Brake";
const char pstrUsageTrigger						[] = "Trigger";
const char pstrUsageWeaponsArm					[] = "Weapons Arm";
const char pstrUsageWeaponsSelect				[] = "Weapons Sel";
const char pstrUsageWingFlaps					[] = "Wing Flaps";
const char pstrUsageAccelerator					[] = "Accel";
const char pstrUsageBrake						[] = "Brake";
const char pstrUsageClutch						[] = "Clutch";
const char pstrUsageShifter						[] = "Shifter";
const char pstrUsageSteering					[] = "Steering";
const char pstrUsageTurretDirection				[] = "Turret Dir";
const char pstrUsageBarrelElevation				[] = "Barrel Ele";
const char pstrUsageDivePlane					[] = "Dive Plane";
const char pstrUsageBallast						[] = "Ballast";
const char pstrUsageBicycleCrank				[] = "Bicycle Crank";
const char pstrUsageHandleBars					[] = "Handle Bars";
const char pstrUsageFrontBrake					[] = "Front Brake";
const char pstrUsageRearBrake					[] = "Rear Brake";

// VR Controls Page
const char pstrUsageBelt						[] = "Belt";
const char pstrUsageBodySuit					[] = "Body Suit";
const char pstrUsageFlexor						[] = "Flexor";
const char pstrUsageGlove						[] = "Glove";
const char pstrUsageHeadTracker					[] = "Head Track";
const char pstrUsageHeadMountedDisplay			[] = "Head Disp";
const char pstrUsageHandTracker					[] = "Hand Track";
const char pstrUsageOculometer					[] = "Oculometer";
const char pstrUsageVest						[] = "Vest";
const char pstrUsageAnimatronicDevice			[] = "Animat Dev";
const char pstrUsageStereoEnable				[] = "Stereo Enbl";
const char pstrUsageDisplayEnable				[] = "Display Enbl";

// Sport Controls Page
const char pstrUsageBaseballBat					[] = "Baseball Bat";
const char pstrUsageGolfClub					[] = "Golf Club";
const char pstrUsageRowingMachine				[] = "Rowing Mach";
const char pstrUsageTreadmill					[] = "Treadmill";
const char pstrUsageOar							[] = "Oar";
const char pstrUsageSlope						[] = "Slope";
const char pstrUsageRate						[] = "Rate";
const char pstrUsageStickSpeed					[] = "Stick Speed";
const char pstrUsageStickFaceAngle				[] = "Stick Face Ang";
const char pstrUsageStickHeelToe				[] = "Stick Heel/Toe";
const char pstrUsageStickFollowThough			[] = "Stick Flw Thru";
const char pstrUsageStickTempo					[] = "Stick Tempo";
const char pstrUsageStickType					[] = "Stick Type";
const char pstrUsageStickHeight					[] = "Stick Hght";
const char pstrUsagePutter						[] = "Putter";
const char pstrUsage1Iron						[] = "1 Iron";
const char pstrUsage2Iron						[] = "2 Iron";
const char pstrUsage3Iron						[] = "3 Iron";
const char pstrUsage4Iron						[] = "4 Iron";
const char pstrUsage5Iron						[] = "5 Iron";
const char pstrUsage6Iron						[] = "6 Iron";
const char pstrUsage7Iron						[] = "7 Iron";
const char pstrUsage8Iron						[] = "8 Iron";
const char pstrUsage9Iron						[] = "9 Iron";
const char pstrUsage10Iron						[] = "10 Iron";
const char pstrUsage11Iron						[] = "11 Iron";
const char pstrUsageSandWedge					[] = "Sand Wedge";
const char pstrUsageLoftWedge					[] = "Loft Wedge";
const char pstrUsagePowerWedge					[] = "Pwr Wedge";
const char pstrUsage1Wood						[] = "1 Wood";
const char pstrUsage3Wood						[] = "3 Wood";
const char pstrUsage5Wood						[] = "5 Wood";
const char pstrUsage7Wood						[] = "7 Wood";
const char pstrUsage9Wood						[] = "9 Wood";

// Game Controls Page
const char pstrUsage3DGameController			[] = "3D Game Ctrl";
const char pstrUsagePinballDevice				[] = "Pinball Dev";
const char pstrUsageGunDevice					[] = "Gun Dev";
const char pstrUsagePointOfView					[] = "POV";
const char pstrUsageTurnRightLeft				[] = "Turn Right Left";
const char pstrUsagePitchForwardBackward		[] = "Pitch Fwd/Back";
const char pstrUsageRollRightLeft				[] = "Roll Right/Left";
const char pstrUsageMoveRightLeft				[] = "Move Right/Left";
const char pstrUsageMoveForwardBackward			[] = "Move Fwd/Back";
const char pstrUsageMoveUpDown					[] = "Move Up/Down";
const char pstrUsageLeanRightLeft				[] = "Lean Right/Left";
const char pstrUsageLeanForwardBackward			[] = "Lean Fwd/Back";
const char pstrUsageHeightOfPOV					[] = "Height of POV";
const char pstrUsageFlipper						[] = "Flipper";
const char pstrUsageSecondaryFlipper			[] = "Second Flipper";
const char pstrUsageBump						[] = "Bump";
const char pstrUsageNewGame						[] = "New Game";
const char pstrUsageShootBall					[] = "Shoot Ball";
const char pstrUsagePlayer						[] = "Player";
const char pstrUsageGunBolt						[] = "Gun Bolt";
const char pstrUsageGunClip						[] = "Gun Clip";
const char pstrUsageGunSelector					[] = "Gun Sel";
const char pstrUsageGunSingleShot				[] = "Gun Sngl Shot";
const char pstrUsageGunBurst					[] = "Gun Burst";
const char pstrUsageGunAutomatic				[] = "Gun Auto";
const char pstrUsageGunSafety					[] = "Gun Safety";
const char pstrUsageGamepadFireJump				[] = "Gamepad Fire/Jump";
const char pstrUsageGamepadTrigger				[] = "Gamepad Trig";

// Generic Device Controls Page
const char pstrUsageBatteryStrength				[] = "Bat Strength";
const char pstrUsageWirelessChannel				[] = "Wireless Ch";
const char pstrUsageWirelessID					[] = "Wireless ID";
const char pstrUsageDiscoverWirelessControl		[] = "Discover Wireless Ctrl";
const char pstrUsageSecurityCodeCharEntered		[] = "Sec Code Char Entrd";
const char pstrUsageSecurityCodeCharErased		[] = "Sec Code Char Erased";
const char pstrUsageSecurityCodeCleared			[] = "Sec Code Cleared";

// LED Page
const char pstrUsageNumLock						[] = "Num Lock";
const char pstrUsageCapsLock					[] = "Caps Lock";
const char pstrUsageScrollLock					[] = "Scroll Lock";
const char pstrUsageCompose						[] = "Compose";
const char pstrUsageKana						[] = "Kana";
const char pstrUsagePower						[] = "Pwr";
const char pstrUsageShift						[] = "Shift";
const char pstrUsageDoNotDisturb				[] = "DND";
const char pstrUsageMute						[] = "Mute";
const char pstrUsageToneEnable					[] = "Tone Enbl";
const char pstrUsageHighCutFilter				[] = "High Cut Fltr";
const char pstrUsageLowCutFilter				[] = "Low Cut Fltr";
const char pstrUsageEqualizerEnable				[] = "Eq Enbl";
const char pstrUsageSoundFieldOn				[] = "Sound Field On";
const char pstrUsageSurroundOn					[] = "Surround On";
const char pstrUsageRepeat						[] = "Repeat";
const char pstrUsageStereo						[] = "Stereo";
const char pstrUsageSamplingRateDetect			[] = "Smpl Rate Detect";
const char pstrUsageSpinning					[] = "Spinning";
const char pstrUsageCAV							[] = "CAV";
const char pstrUsageCLV							[] = "CLV";
const char pstrUsageRecordingFormatDetect		[] = "Rec Format Detect";
const char pstrUsageOffHook						[] = "Off Hook";
const char pstrUsageRing						[] = "Ring";
const char pstrUsageMessageWaiting				[] = "Msg Wait";
const char pstrUsageDataMode					[] = "Data Mode";
const char pstrUsageBatteryOperation			[] = "Bat Op";
const char pstrUsageBatteryOK					[] = "Bat OK";
const char pstrUsageBatteryLow					[] = "Bat Low";
const char pstrUsageSpeaker						[] = "Speaker";
const char pstrUsageHeadSet						[] = "Head Set";
const char pstrUsageHold						[] = "Hold";
const char pstrUsageMicrophone					[] = "Mic";
const char pstrUsageCoverage					[] = "Coverage";
const char pstrUsageNightMode					[] = "Night Mode";
const char pstrUsageSendCalls					[] = "Send Calls";
const char pstrUsageCallPickup					[] = "Call Pickup";
const char pstrUsageConference					[] = "Conf";
const char pstrUsageStandBy						[] = "Stand-by";
const char pstrUsageCameraOn					[] = "Cam On";
const char pstrUsageCameraOff					[] = "Cam Off";
const char pstrUsageOnLine						[] = "On-Line";
const char pstrUsageOffLine						[] = "Off-Line";
const char pstrUsageBusy						[] = "Busy";
const char pstrUsageReady						[] = "Ready";
const char pstrUsagePaperOut					[] = "Paper Out";
const char pstrUsagePaperJam					[] = "Paper Jam";
const char pstrUsageRemote						[] = "Remote";
const char pstrUsageForward						[] = "Fwd";
const char pstrUsageReverse						[] = "Rev";
const char pstrUsageStop						[] = "Stop";
const char pstrUsageRewind						[] = "Rewind";
const char pstrUsageFastForward					[] = "Fast Fwd";
const char pstrUsagePlay						[] = "Play";
const char pstrUsagePause						[] = "Pause";
const char pstrUsageRecord						[] = "Rec";
const char pstrUsageError						[] = "Error";
const char pstrUsageSelectedIndicator			[] = "Usage Sel Ind";
const char pstrUsageInUseIndicator				[] = "Usage In Use Ind";
const char pstrUsageMultiModeIndicator			[] = "Usage Multi Mode Ind";
const char pstrUsageIndicatorOn					[] = "Ind On";
const char pstrUsageIndicatorFlash				[] = "Ind Flash";
const char pstrUsageIndicatorSlowBlink			[] = "Ind Slow Blk";
const char pstrUsageIndicatorFastBlink			[] = "Ind Fast Blk";
const char pstrUsageIndicatorOff				[] = "Ind Off";
const char pstrUsageFlashOnTime					[] = "Flash On Time";
const char pstrUsageSlowBlinkOnTime				[] = "Slow Blk On Time";
const char pstrUsageSlowBlinkOffTime			[] = "Slow Blk Off Time";
const char pstrUsageFastBlinkOnTime				[] = "Fast Blk On Time";
const char pstrUsageFastBlinkOffTime			[] = "Fast Blk Off Time";
const char pstrUsageIndicatorColor				[] = "Usage Ind Color";
const char pstrUsageIndicatorRed				[] = "Ind Red";
const char pstrUsageIndicatorGreen				[] = "Ind Green";
const char pstrUsageIndicatorAmber				[] = "Ind Amber";
const char pstrUsageGenericIndicator			[] = "Gen Ind";
const char pstrUsageSystemSuspend				[] = "Sys Suspend";
const char pstrUsageExternalPowerConnected		[] = "Ext Pwr Conn";

// Telephony Usage Page
const char pstrUsagePhone						[] = "Phone";
const char pstrUsageAnsweringMachine			[] = "Answ Mach";
const char pstrUsageMessageControls				[] = "Msg Ctrls";
const char pstrUsageHandset						[] = "Handset";
const char pstrUsageHeadset						[] = "Headset";
const char pstrUsageTelephonyKeyPad				[] = "Tel Key Pad";
const char pstrUsageProgrammableButton			[] = "Prog Button";
const char pstrUsageHookSwitch					[] = "Hook Sw";
const char pstrUsageFlash						[] = "Flash";
const char pstrUsageFeature						[] = "Feature";
//const char pstrUsageHold						[] = "Hold";
const char pstrUsageRedial						[] = "Redial";
const char pstrUsageTransfer					[] = "Transfer";
const char pstrUsageDrop						[] = "Drop";
const char pstrUsagePark						[] = "Park";
const char pstrUsageForwardCalls				[] = "Fwd Calls";
const char pstrUsageAlternateFunction			[] = "Alt Func";
const char pstrUsageLine						[] = "Line";
const char pstrUsageSpeakerPhone				[] = "Spk Phone";
//const char pstrUsageConference					[] = "Conference";
const char pstrUsageRingEnable					[] = "Ring Enbl";
const char pstrUsageRingSelect					[] = "Ring Sel";
const char pstrUsagePhoneMute					[] = "Phone Mute";
const char pstrUsageCallerID					[] = "Caller ID";
const char pstrUsageSend						[] = "Send";
const char pstrUsageSpeedDial					[] = "Speed Dial";
const char pstrUsageStoreNumber					[] = "Store Num";
const char pstrUsageRecallNumber				[] = "Recall Num";
const char pstrUsagePhoneDirectory				[] = "Phone Dir";
const char pstrUsageVoiceMail					[] = "Voice Mail";
const char pstrUsageScreenCalls					[] = "Screen Calls";
//const char pstrUsageDoNotDisturb				[] = "Do Not Disturb";
const char pstrUsageMessage						[] = "Msg";
const char pstrUsageAnswerOnOff					[] = "Answer On/Off";
const char pstrUsageInsideDialTone				[] = "Inside Dial Tone";
const char pstrUsageOutsideDialTone				[] = "Outside Dial Tone";
const char pstrUsageInsideRingTone				[] = "Inside Ring Tone";
const char pstrUsageOutsideRingTone				[] = "Outside Ring Tone";
const char pstrUsagePriorityRingTone			[] = "Prior Ring Tone";
const char pstrUsageInsideRingback				[] = "Inside Ringback";
const char pstrUsagePriorityRingback			[] = "Priority Ringback";
const char pstrUsageLineBusyTone				[] = "Ln Busy Tone";
const char pstrUsageReorderTone					[] = "Reorder Tone";
const char pstrUsageCallWaitingTone				[] = "Call Wait Tone";
const char pstrUsageConfirmationTone1			[] = "Cnfrm Tone1";
const char pstrUsageConfirmationTone2			[] = "Cnfrm Tone2";
const char pstrUsageTonesOff					[] = "Tones Off";
const char pstrUsageOutsideRingback				[] = "Outside Ringback";
const char pstrUsageRinger						[] = "Ringer";
const char pstrUsagePhoneKey0					[] = "0";
const char pstrUsagePhoneKey1					[] = "1";
const char pstrUsagePhoneKey2					[] = "2";
const char pstrUsagePhoneKey3					[] = "3";
const char pstrUsagePhoneKey4					[] = "4";
const char pstrUsagePhoneKey5					[] = "5";
const char pstrUsagePhoneKey6					[] = "6";
const char pstrUsagePhoneKey7					[] = "7";
const char pstrUsagePhoneKey8					[] = "8";
const char pstrUsagePhoneKey9					[] = "9";
const char pstrUsagePhoneKeyStar				[] = "*";
const char pstrUsagePhoneKeyPound				[] = "#";
const char pstrUsagePhoneKeyA					[] = "A";
const char pstrUsagePhoneKeyB					[] = "B";
const char pstrUsagePhoneKeyC					[] = "C";
const char pstrUsagePhoneKeyD					[] = "D";

// Consumer Usage Page
const char pstrUsageConsumerControl				[] = "Consumer Ctrl";
const char pstrUsageNumericKeyPad				[] = "Num Key Pad";
//const char pstrUsageProgrammableButton			[] = "Prog Btn";
//const char pstrUsageMicrophone					[] = "Mic";
const char pstrUsageHeadphone					[] = "Headphone";
const char pstrUsageGraphicEqualizer			[] = "Graph Eq";
const char pstrUsagePlus10						[] = "+10";
const char pstrUsagePlus100						[] = "+100";
const char pstrUsageAMPM						[] = "AM/PM";
//const char pstrUsagePower						[] = "Pwr";
const char pstrUsageReset						[] = "Reset";
const char pstrUsageSleep						[] = "Sleep";
const char pstrUsageSleepAfter					[] = "Sleep After";
const char pstrUsageSleepMode					[] = "Sleep Mode";
const char pstrUsageIllumination				[] = "Illumin";
const char pstrUsageFunctionButtons				[] = "Func Btns";
const char pstrUsageMenu						[] = "Menu";
const char pstrUsageMenuPick					[] = "Menu Pick";
const char pstrUsageMenuUp						[] = "Menu Up";
const char pstrUsageMenuDown					[] = "Menu Down";
const char pstrUsageMenuLeft					[] = "Menu Left";
const char pstrUsageMenuRight					[] = "Menu Right";
const char pstrUsageMenuEscape					[] = "Menu Esc";
const char pstrUsageMenuValueIncrease			[] = "Menu Val Inc";
const char pstrUsageMenuValueDecrease			[] = "Menu Val Dec";
const char pstrUsageDataOnScreen				[] = "Data On Scr";
const char pstrUsageClosedCaption				[] = "Closed Cptn";
const char pstrUsageClosedCaptionSelect			[] = "Closed Cptn Sel";
const char pstrUsageVCRTV						[] = "VCR/TV";
const char pstrUsageBroadcastMode				[] = "Brdcast Mode";
const char pstrUsageSnapshot					[] = "Snapshot";
const char pstrUsageStill						[] = "Still";
const char pstrUsageSelection					[] = "Sel";
const char pstrUsageAssignSelection				[] = "Assign Sel";
const char pstrUsageModeStep					[] = "Mode Step";
const char pstrUsageRecallLast					[] = "Recall Last";
const char pstrUsageEnterChannel				[] = "Entr Channel";
const char pstrUsageOrderMovie					[] = "Ord Movie";
const char pstrUsageChannel						[] = "Channel";
const char pstrUsageMediaSelection				[] = "Med Sel";
const char pstrUsageMediaSelectComputer			[] = "Med Sel Comp";
const char pstrUsageMediaSelectTV				[] = "Med Sel TV";
const char pstrUsageMediaSelectWWW				[] = "Med Sel WWW";
const char pstrUsageMediaSelectDVD				[] = "Med Sel DVD";
const char pstrUsageMediaSelectTelephone		[] = "Med Sel Tel";
const char pstrUsageMediaSelectProgramGuide		[] = "Med Sel PG";
const char pstrUsageMediaSelectVideoPhone		[] = "Med Sel Vid";
const char pstrUsageMediaSelectGames			[] = "Med Sel Games";
const char pstrUsageMediaSelectMessages			[] = "Med Sel Msg";
const char pstrUsageMediaSelectCD				[] = "Med Sel CD";
const char pstrUsageMediaSelectVCR				[] = "Med Sel VCR";
const char pstrUsageMediaSelectTuner			[] = "Med Sel Tuner";
const char pstrUsageQuit						[] = "Quit";
const char pstrUsageHelp						[] = "Help";
const char pstrUsageMediaSelectTape				[] = "Med Sel Tape";
const char pstrUsageMediaSelectCable			[] = "Med Sel Cbl";
const char pstrUsageMediaSelectSatellite		[] = "Med Sel Sat";
const char pstrUsageMediaSelectSecurity			[] = "Med Sel Secur";
const char pstrUsageMediaSelectHome				[] = "Med Sel Home";
const char pstrUsageMediaSelectCall				[] = "Med Sel Call";
const char pstrUsageChannelIncrement			[] = "Ch Inc";
const char pstrUsageChannelDecrement			[] = "Ch Dec";
const char pstrUsageMediaSelectSAP				[] = "Med Sel SAP";
const char pstrUsageVCRPlus						[] = "VCR+";
const char pstrUsageOnce						[] = "Once";
const char pstrUsageDaily						[] = "Daily";
const char pstrUsageWeekly						[] = "Weekly";
const char pstrUsageMonthly						[] = "Monthly";
//const char pstrUsagePlay						[] = "Play";
//const char pstrUsagePause						[] = "Pause";
//const char pstrUsageRecord						[] = "Rec";
//const char pstrUsageFastForward					[] = "FF";
//const char pstrUsageRewind						[] = "Rewind";
const char pstrUsageScanNextTrack				[] = "Next Track";
const char pstrUsageScanPreviousTrack			[] = "Prev Track";
//const char pstrUsageStop						[] = "Stop";
const char pstrUsageEject						[] = "Eject";
const char pstrUsageRandomPlay					[] = "Random";
const char pstrUsageSelectDisk					[] = "Sel Disk";
const char pstrUsageEnterDisk					[] = "Ent Disk";
//const char pstrUsageRepeat						[] = "Repeat";
const char pstrUsageTracking					[] = "Tracking";
const char pstrUsageTrackNormal					[] = "Trk Norm";
const char pstrUsageSlowTracking				[] = "Slow Trk";
const char pstrUsageFrameForward				[] = "Frm Fwd";
const char pstrUsageFrameBackwards				[] = "Frm Back";
const char pstrUsageMark						[] = "Mark";
const char pstrUsageClearMark					[] = "Clr Mark";
const char pstrUsageRepeatFromMark				[] = "Rpt Mark";
const char pstrUsageReturnToMark				[] = "Ret to Mark";
const char pstrUsageSearchMarkForward			[] = "Search Mark Fwd";
const char pstrUsageSearchMarkBackwards			[] = "Search Mark Back";
const char pstrUsageCounterReset				[] = "Counter Reset";
const char pstrUsageShowCounter					[] = "Show Counter";
const char pstrUsageTrackingIncrement			[] = "Track Inc";
const char pstrUsageTrackingDecrement			[] = "Track Dec";
const char pstrUsageStopEject					[] = "Stop/Eject";
const char pstrUsagePlayPause					[] = "Play/Pause";
const char pstrUsagePlaySkip					[] = "Play/Skip";
const char pstrUsageVolume						[] = "Vol";
const char pstrUsageBalance						[] = "Balance";
//const char pstrUsageMute						[] = "Mute";
const char pstrUsageBass						[] = "Bass";
const char pstrUsageTreble						[] = "Treble";
const char pstrUsageBassBoost					[] = "Bass Boost";
const char pstrUsageSurroundMode				[] = "Surround";
const char pstrUsageLoudness					[] = "Loud";
const char pstrUsageMPX							[] = "MPX";
const char pstrUsageVolumeIncrement				[] = "Vol Inc";
const char pstrUsageVolumeDecrement				[] = "Vol Dec";
const char pstrUsageSpeedSelect					[] = "Speed";
const char pstrUsagePlaybackSpeed				[] = "Play Speed";
const char pstrUsageStandardPlay				[] = "Std Play";
const char pstrUsageLongPlay					[] = "Long Play";
const char pstrUsageExtendedPlay				[] = "Ext Play";
const char pstrUsageSlow						[] = "Slow";
const char pstrUsageFanEnable					[] = "Fan Enbl";
const char pstrUsageFanSpeed					[] = "Fan Speed";
const char pstrUsageLightEnable					[] = "Light Enbl";
const char pstrUsageLightIlluminationLevel		[] = "Light Illum Lev";
const char pstrUsageClimateControlEnable		[] = "Climate Enbl";
const char pstrUsageRoomTemperature				[] = "Room Temp";
const char pstrUsageSecurityEnable				[] = "Secur Enbl";
const char pstrUsageFireAlarm					[] = "Fire Alm";
const char pstrUsagePoliceAlarm					[] = "Police Alm";
const char pstrUsageProximity					[] = "Prox";
const char pstrUsageMotion						[] = "Motion";
const char pstrUsageDuresAlarm					[] = "Dures Alm";
const char pstrUsageHoldupAlarm					[] = "Holdup Alm";
const char pstrUsageMedicalAlarm				[] = "Med Alm";
const char pstrUsageBalanceRight				[] = "Balance Right";
const char pstrUsageBalanceLeft					[] = "Balance Left";
const char pstrUsageBassIncrement				[] = "Bass Inc";
const char pstrUsageBassDecrement				[] = "Bass Dec";
const char pstrUsageTrebleIncrement				[] = "Treble Inc";
const char pstrUsageTrebleDecrement				[] = "Treble Dec";
const char pstrUsageSpeakerSystem				[] = "Spk Sys";
const char pstrUsageChannelLeft					[] = "Ch Left";
const char pstrUsageChannelRight				[] = "Ch Right";
const char pstrUsageChannelCenter				[] = "Ch Center";
const char pstrUsageChannelFront				[] = "Ch Front";
const char pstrUsageChannelCenterFront			[] = "Ch Cntr Front";
const char pstrUsageChannelSide					[] = "Ch Side";
const char pstrUsageChannelSurround				[] = "Ch Surround";
const char pstrUsageChannelLowFreqEnhancement	[] = "Ch Low Freq Enh";
const char pstrUsageChannelTop					[] = "Ch Top";
const char pstrUsageChannelUnknown				[] = "Ch Unk";
const char pstrUsageSubChannel					[] = "Sub-ch";
const char pstrUsageSubChannelIncrement			[] = "Sub-ch Inc";
const char pstrUsageSubChannelDecrement			[] = "Sub-ch Dec";
const char pstrUsageAlternateAudioIncrement		[] = "Alt Aud Inc";
const char pstrUsageAlternateAudioDecrement		[] = "Alt Aud Dec";
const char pstrUsageApplicationLaunchButtons	[] = "App Launch Btns";
const char pstrUsageALLaunchButtonConfigTool	[] = "AL Launch Conf Tl";
const char pstrUsageALProgrammableButton		[] = "AL Pgm Btn";
const char pstrUsageALConsumerControlConfig		[] = "AL Cons Ctrl Cfg";
const char pstrUsageALWordProcessor				[] = "AL Word Proc";
const char pstrUsageALTextEditor				[] = "AL Txt Edtr";
const char pstrUsageALSpreadsheet				[] = "AL Sprdsheet";
const char pstrUsageALGraphicsEditor			[] = "AL Graph Edtr";
const char pstrUsageALPresentationApp			[] = "AL Present App";
const char pstrUsageALDatabaseApp				[] = "AL DB App";
const char pstrUsageALEmailReader				[] = "AL E-mail Rdr";
const char pstrUsageALNewsreader				[] = "AL Newsrdr";
const char pstrUsageALVoicemail					[] = "AL Voicemail";
const char pstrUsageALContactsAddressBook		[] = "AL Addr Book";
const char pstrUsageALCalendarSchedule			[] = "AL Clndr/Schdlr";
const char pstrUsageALTaskProjectManager		[] = "AL Task/Prj Mgr";
const char pstrUsageALLogJournalTimecard		[] = "AL Log/Jrnl/Tmcrd";
const char pstrUsageALCheckbookFinance			[] = "AL Chckbook/Fin";
const char pstrUsageALCalculator				[] = "AL Calc";
const char pstrUsageALAVCapturePlayback			[] = "AL A/V Capt/Play";
const char pstrUsageALLocalMachineBrowser		[] = "AL Loc Mach Brow";
const char pstrUsageALLANWANBrow				[] = "AL LAN/WAN Brow";
const char pstrUsageALInternetBrowser			[] = "AL I-net Brow";
const char pstrUsageALRemoteNetISPConnect		[] = "AL Rem Net Con";
const char pstrUsageALNetworkConference			[] = "AL Net Conf";
const char pstrUsageALNetworkChat				[] = "AL Net Chat";
const char pstrUsageALTelephonyDialer			[] = "AL Tel/Dial";
const char pstrUsageALLogon						[] = "AL Logon";
const char pstrUsageALLogoff					[] = "AL Logoff";
const char pstrUsageALLogonLogoff				[] = "AL Logon/Logoff";
const char pstrUsageALTermLockScrSav			[] = "AL Term Lock/Scr Sav";
const char pstrUsageALControlPannel				[] = "AL Ctrl Pan";
const char pstrUsageALCommandLineProcessorRun	[] = "AL Cmd/Run";
const char pstrUsageALProcessTaskManager		[] = "AL Task Mgr";
const char pstrUsageALSelectTaskApplication		[] = "AL Sel App";
const char pstrUsageALNextTaskApplication		[] = "AL Next App";
const char pstrUsageALPreviousTaskApplication	[] = "AL Prev App";
const char pstrUsageALPreemptiveHaltTaskApp		[] = "AL Prmpt Halt App";
const char pstrUsageALIntegratedHelpCenter		[] = "AL Hlp Cntr";
const char pstrUsageALDocuments					[] = "AL Docs";
const char pstrUsageALThesaurus					[] = "AL Thsrs";
const char pstrUsageALDictionary				[] = "AL Dict";
const char pstrUsageALDesktop					[] = "AL Desktop";
const char pstrUsageALSpellCheck				[] = "AL Spell Chk";
const char pstrUsageALGrammarCheck				[] = "AL Gram Chk";
const char pstrUsageALWirelessStatus			[] = "AL Wireless Sts";
const char pstrUsageALKeyboardLayout			[] = "AL Kbd Layout";
const char pstrUsageALVirusProtection			[] = "AL Vir Protect";
const char pstrUsageALEncryption				[] = "AL Encrypt";
const char pstrUsageALScreenSaver				[] = "AL Scr Sav";
const char pstrUsageALAlarms					[] = "AL Alarms";
const char pstrUsageALClock						[] = "AL Clock";
const char pstrUsageALFileBrowser				[] = "AL File Brow";
const char pstrUsageALPowerStatus				[] = "AL Pwr Sts";
const char pstrUsageALImageBrowser				[] = "AL Img Brow";
const char pstrUsageALAudioBrowser				[] = "AL Aud Brow";
const char pstrUsageALMovieBrowser				[] = "AL Mov Brow";
const char pstrUsageALDigitalRightsManager		[] = "AL Dig Rights Mgr";
const char pstrUsageALDigitalWallet				[] = "AL Dig Wallet";
const char pstrUsageALInstantMessaging			[] = "AL Inst Msg";
const char pstrUsageALOEMFeaturesBrowser		[] = "AL OEM Tips Brow";
const char pstrUsageALOEMHelp					[] = "AL OEM Hlp";
const char pstrUsageALOnlineCommunity			[] = "AL Online Com";
const char pstrUsageALEntertainmentContentBrow	[] = "AL Ent Cont Brow";
const char pstrUsageALOnlineShoppingBrowser		[] = "AL Online Shop Brow";
const char pstrUsageALSmartCardInfoHelp			[] = "AL SmartCard Inf";
const char pstrUsageALMarketMonitorFinBrowser	[] = "AL Market Brow";
const char pstrUsageALCustomCorpNewsBrowser		[] = "AL Cust Corp News Brow";
const char pstrUsageALOnlineActivityBrowser		[] = "AL Online Act Brow";
const char pstrUsageALResearchSearchBrowser		[] = "AL Search Brow";
const char pstrUsageALAudioPlayer				[] = "AL Aud Player";
const char pstrUsageGenericGUIAppControls		[] = "Gen GUI App Ctrl";
const char pstrUsageACNew						[] = "AC New";
const char pstrUsageACOpen						[] = "AC Open";
const char pstrUsageACClose						[] = "AC Close";
const char pstrUsageACExit						[] = "AC Exit";
const char pstrUsageACMaximize					[] = "AC Max";
const char pstrUsageACMinimize					[] = "AC Min";
const char pstrUsageACSave						[] = "AC Save";
const char pstrUsageACPrint						[] = "AC Print";
const char pstrUsageACProperties				[] = "AC Prop";
const char pstrUsageACUndo						[] = "AC Undo";
const char pstrUsageACCopy						[] = "AC Copy";
const char pstrUsageACCut						[] = "AC Cut";
const char pstrUsageACPaste						[] = "AC Paste";
const char pstrUsageACSelectAll					[] = "AC Sel All";
const char pstrUsageACFind						[] = "AC Find";
const char pstrUsageACFindAndReplace			[] = "AC Find/Replace";
const char pstrUsageACSearch					[] = "AC Search";
const char pstrUsageACGoto						[] = "AC Goto";
const char pstrUsageACHome						[] = "AC Home";
const char pstrUsageACBack						[] = "AC Back";
const char pstrUsageACForward					[] = "AC Fwd";
const char pstrUsageACStop						[] = "AC Stop";
const char pstrUsageACRefresh					[] = "AC Refresh";
const char pstrUsageACPreviousLink				[] = "AC Prev Link";
const char pstrUsageACNextLink					[] = "AC Next Link";
const char pstrUsageACBookmarks					[] = "AC Bkmarks";
const char pstrUsageACHistory					[] = "AC Hist";
const char pstrUsageACSubscriptions				[] = "AC Subscr";
const char pstrUsageACZoomIn					[] = "AC Zoom In";
const char pstrUsageACZoomOut					[] = "AC Zoom Out";
const char pstrUsageACZoom						[] = "AC Zoom";
const char pstrUsageACFullScreenView			[] = "AC Full Scr";
const char pstrUsageACNormalView				[] = "AC Norm View";
const char pstrUsageACViewToggle				[] = "AC View Tgl";
const char pstrUsageACScrollUp					[] = "AC Scroll Up";
const char pstrUsageACScrollDown				[] = "AC Scroll Down";
const char pstrUsageACScroll					[] = "AC Scroll";
const char pstrUsageACPanLeft					[] = "AC Pan Left";
const char pstrUsageACPanRight					[] = "AC Pan Right";
const char pstrUsageACPan						[] = "AC Pan";
const char pstrUsageACNewWindow					[] = "AC New Wnd";
const char pstrUsageACTileHoriz					[] = "AC Tile Horiz";
const char pstrUsageACTileVert					[] = "AC Tile Vert";
const char pstrUsageACFormat					[] = "AC Frmt";
const char pstrUsageACEdit						[] = "AC Edit";
const char pstrUsageACBold						[] = "AC Bold";
const char pstrUsageACItalics					[] = "AC Ital";
const char pstrUsageACUnderline					[] = "AC Under";
const char pstrUsageACStrikethrough				[] = "AC Strike";
const char pstrUsageACSubscript					[] = "AC Sub";
const char pstrUsageACSuperscript				[] = "AC Super";
const char pstrUsageACAllCaps					[] = "AC All Caps";
const char pstrUsageACRotate					[] = "AC Rotate";
const char pstrUsageACResize					[] = "AC Resize";
const char pstrUsageACFlipHorizontal			[] = "AC Flp H";
const char pstrUsageACFlipVertical				[] = "AC Flp V";
const char pstrUsageACMirrorHorizontal			[] = "AC Mir H";
const char pstrUsageACMirrorVertical			[] = "AC Mir V";
const char pstrUsageACFontSelect				[] = "AC Fnt Sel";
const char pstrUsageACFontColor					[] = "AC Fnt Clr";
const char pstrUsageACFontSize					[] = "AC Fnt Size";
const char pstrUsageACJustifyLeft				[] = "AC Just Left";
const char pstrUsageACJustifyCenterH			[] = "AC Just Cent H";
const char pstrUsageACJustifyRight				[] = "AC Just Right";
const char pstrUsageACJustifyBlockH				[] = "AC Just Block H";
const char pstrUsageACJustifyTop				[] = "AC Just Top";
const char pstrUsageACJustifyCenterV			[] = "AC Just Cent V";
const char pstrUsageACJustifyBottom				[] = "AC Just Bot";
const char pstrUsageACJustifyBlockV				[] = "AC Just Block V";
const char pstrUsageACIndentDecrease			[] = "AC Indent Dec";
const char pstrUsageACIndentIncrease			[] = "AC Indent Inc";
const char pstrUsageACNumberedList				[] = "AC Num List";
const char pstrUsageACRestartNumbering			[] = "AC Res Num";
const char pstrUsageACBulletedList				[] = "AC Blt List";
const char pstrUsageACPromote					[] = "AC Promote";
const char pstrUsageACDemote					[] = "AC Demote";
const char pstrUsageACYes						[] = "AC Yes";
const char pstrUsageACNo						[] = "AC No";
const char pstrUsageACCancel					[] = "AC Cancel";
const char pstrUsageACCatalog					[] = "AC Ctlg";
const char pstrUsageACBuyChkout					[] = "AC Buy";
const char pstrUsageACAddToCart					[] = "AC Add2Cart";
const char pstrUsageACExpand					[] = "AC Xpnd";
const char pstrUsageACExpandAll					[] = "AC Xpand All";
const char pstrUsageACCollapse					[] = "AC Collapse";
const char pstrUsageACCollapseAll				[] = "AC Collapse All";
const char pstrUsageACPrintPreview				[] = "AC Prn Prevw";
const char pstrUsageACPasteSpecial				[] = "AC Paste Spec";
const char pstrUsageACInsertMode				[] = "AC Ins Mode";
const char pstrUsageACDelete					[] = "AC Del";
const char pstrUsageACLock						[] = "AC Lock";
const char pstrUsageACUnlock					[] = "AC Unlock";
const char pstrUsageACProtect					[] = "AC Prot";
const char pstrUsageACUnprotect					[] = "AC Unprot";
const char pstrUsageACAttachComment				[] = "AC Attach Cmnt";
const char pstrUsageACDeleteComment				[] = "AC Del Cmnt";
const char pstrUsageACViewComment				[] = "AC View Cmnt";
const char pstrUsageACSelectWord				[] = "AC Sel Word";
const char pstrUsageACSelectSentence			[] = "AC Sel Sntc";
const char pstrUsageACSelectParagraph			[] = "AC Sel Para";
const char pstrUsageACSelectColumn				[] = "AC Sel Col";
const char pstrUsageACSelectRow					[] = "AC Sel Row";
const char pstrUsageACSelectTable				[] = "AC Sel Tbl";
const char pstrUsageACSelectObject				[] = "AC Sel Obj";
const char pstrUsageACRedoRepeat				[] = "AC Redo";
const char pstrUsageACSort						[] = "AC Sort";
const char pstrUsageACSortAscending				[] = "AC Sort Asc";
const char pstrUsageACSortDescending			[] = "AC Sort Desc";
const char pstrUsageACFilter					[] = "AC Filt";
const char pstrUsageACSetClock					[] = "AC Set Clk";
const char pstrUsageACViewClock					[] = "AC View Clk";
const char pstrUsageACSelectTimeZone			[] = "AC Sel Time Z";
const char pstrUsageACEditTimeZone				[] = "AC Edt Time Z";
const char pstrUsageACSetAlarm					[] = "AC Set Alm";
const char pstrUsageACClearAlarm				[] = "AC Clr Alm";
const char pstrUsageACSnoozeAlarm				[] = "AC Snz Alm";
const char pstrUsageACResetAlarm				[] = "AC Rst Alm";
const char pstrUsageACSyncronize				[] = "AC Sync";
const char pstrUsageACSendReceive				[] = "AC Snd/Rcv";
const char pstrUsageACSendTo					[] = "AC Snd To";
const char pstrUsageACReply						[] = "AC Reply";
const char pstrUsageACReplyAll					[] = "AC Reply All";
const char pstrUsageACForwardMessage			[] = "AC Fwd Msg";
const char pstrUsageACSend						[] = "AC Snd";
const char pstrUsageACAttachFile				[] = "AC Att File";
const char pstrUsageACUpload					[] = "AC Upld";
const char pstrUsageACDownload					[] = "AC Dnld";
const char pstrUsageACSetBorders				[] = "AC Set Brd";
const char pstrUsageACInsertRow					[] = "AC Ins Row";
const char pstrUsageACInsertColumn				[] = "AC Ins Col";
const char pstrUsageACInsertFile				[] = "AC Ins File";
const char pstrUsageACInsertPicture				[] = "AC Ins Pic";
const char pstrUsageACInsertObject				[] = "AC Ins Obj";
const char pstrUsageACInsertSymbol				[] = "AC Ins Sym";
const char pstrUsageACSaveAndClose				[] = "AC Sav&Cls";
const char pstrUsageACRename					[] = "AC Rename";
const char pstrUsageACMerge						[] = "AC Merge";
const char pstrUsageACSplit						[] = "AC Split";
const char pstrUsageACDistributeHorizontaly		[] = "AC Dist Hor";
const char pstrUsageACDistributeVerticaly		[] = "AC Dist Ver";

// Digitaizers
const char pstrUsageDigitizer					[] = "Digitizer";
const char pstrUsagePen							[] = "Pen";
const char pstrUsageLightPen					[] = "Light Pen";
const char pstrUsageTouchScreen					[] = "Touch Scr";
const char pstrUsageTouchPad					[] = "Touch Pad";
const char pstrUsageWhiteBoard					[] = "White Brd";
const char pstrUsageCoordinateMeasuringMachine	[] = "Coord Meas Mach";
const char pstrUsage3DDigitizer					[] = "3D Dgtz";
const char pstrUsageStereoPlotter				[] = "Stereo Plot";
const char pstrUsageArticulatedArm				[] = "Art Arm";
const char pstrUsageArmature					[] = "Armature";
const char pstrUsageMultiplePointDigitizer		[] = "Multi Point Dgtz";
const char pstrUsageFreeSpaceWand				[] = "Free Space Wand";
const char pstrUsageStylus						[] = "Stylus";
const char pstrUsagePuck						[] = "Puck";
const char pstrUsageFinger						[] = "Finger";
const char pstrUsageTipPressure					[] = "Tip Press";
const char pstrUsageBarrelPressure				[] = "Brl Press";
const char pstrUsageInRange						[] = "In Range";
const char pstrUsageTouch						[] = "Touch";
const char pstrUsageUntouch						[] = "Untouch";
const char pstrUsageTap							[] = "Tap";
const char pstrUsageQuality						[] = "Qlty";
const char pstrUsageDataValid					[] = "Data Valid";
const char pstrUsageTransducerIndex				[] = "Transducer Ind";
const char pstrUsageTabletFunctionKeys			[] = "Tabl Func Keys";
const char pstrUsageProgramChangeKeys			[] = "Pgm Chng Keys";
//const char pstrUsageBatteryStrength				[] = "Bat Strength";
const char pstrUsageInvert						[] = "Invert";
const char pstrUsageXTilt						[] = "X Tilt";
const char pstrUsageYTilt						[] = "Y Tilt";
const char pstrUsageAzimuth						[] = "Azimuth";
const char pstrUsageAltitude					[] = "Altitude";
const char pstrUsageTwist						[] = "Twist";
const char pstrUsageTipSwitch					[] = "Tip Sw";
const char pstrUsageSecondaryTipSwitch			[] = "Scnd Tip Sw";
const char pstrUsageBarrelSwitch				[] = "Brl Sw";
const char pstrUsageEraser						[] = "Eraser";
const char pstrUsageTabletPick					[] = "Tbl Pick";

// Alphanumeric Display Page
const char pstrUsageAlphanumericDisplay			[] = "Alphanum Disp";
const char pstrUsageBitmappedDisplay			[] = "Bmp Disp";
const char pstrUsageDisplayAttributesReport		[] = "Disp Attr Rpt";
const char pstrUsageASCIICharacterSet			[] = "ASCII chset";
const char pstrUsageDataReadBack				[] = "Data Rd Back";
const char pstrUsageFontReadBack				[] = "Fnt Rd Back";
const char pstrUsageDisplayControlReport		[] = "Disp Ctrl Rpt";
const char pstrUsageClearDisplay				[] = "Clr Disp";
//const char pstrUsageDisplayEnable				[] = "Disp Enbl";
const char pstrUsageScreenSaverDelay			[] = "Scr Sav Delay";
const char pstrUsageScreenSaverEnable			[] = "Scr Sav Enbl";
const char pstrUsageVerticalScroll				[] = "V Scroll";
const char pstrUsageHorizontalScroll			[] = "H Scroll";
const char pstrUsageCharacterReport				[] = "Char Rpt";
const char pstrUsageDisplayData					[] = "Disp Data";
const char pstrUsageDisplayStatus				[] = "Disp Stat";
const char pstrUsageStatusNotReady				[] = "Stat !Ready";
const char pstrUsageStatusReady					[] = "Stat Ready";
const char pstrUsageErrorNotALoadableCharacter	[] = "Err Not Ld Char";
const char pstrUsageErrorFotDataCanNotBeRead	[] = "Fnt Data Rd Err";
const char pstrUsageCursorPositionReport		[] = "Cur Pos Rpt";
const char pstrUsageRow							[] = "Row";
const char pstrUsageColumn						[] = "Col";
const char pstrUsageRows						[] = "Rows";
const char pstrUsageColumns						[] = "Cols";
const char pstrUsageCursorPixelPosition			[] = "Cur Pix Pos";
const char pstrUsageCursorMode					[] = "Cur Mode";
const char pstrUsageCursorEnable				[] = "Cur Enbl";
const char pstrUsageCursorBlink					[] = "Cur Blnk";
const char pstrUsageFontReport					[] = "Fnt Rpt";
const char pstrUsageFontData					[] = "Fnt Data";
const char pstrUsageCharacterWidth				[] = "Char Wdth";
const char pstrUsageCharacterHeight				[] = "Char Hght";
const char pstrUsageCharacterSpacingHorizontal	[] = "Char Space H";
const char pstrUsageCharacterSpacingVertical	[] = "Char Space V";
const char pstrUsageUnicodeCharset				[] = "Unicode Char";
const char pstrUsageFont7Segment				[] = "Fnt 7-seg";
const char pstrUsage7SegmentDirectMap			[] = "7-seg map";
const char pstrUsageFont14Segment				[] = "Fnt 14-seg";
const char pstrUsage14SegmentDirectMap			[] = "14-seg map";
const char pstrUsageDisplayBrightness			[] = "Disp Bright";
const char pstrUsageDisplayContrast				[] = "Disp Cntrst";
const char pstrUsageCharacterAttribute			[] = "Char Attr";
const char pstrUsageAttributeReadback			[] = "Attr Readbk";
const char pstrUsageAttributeData				[] = "Attr Data";
const char pstrUsageCharAttributeEnhance		[] = "Char Attr Enh";
const char pstrUsageCharAttributeUnderline		[] = "Char Attr Undl";
const char pstrUsageCharAttributeBlink			[] = "Char Attr Blnk";
const char pstrUsageBitmapSizeX					[] = "Bmp Size X";
const char pstrUsageBitmapSizeY					[] = "Bmp Size Y";
const char pstrUsageBitDepthFormat				[] = "Bit Dpth Fmt";
const char pstrUsageDisplayOrientation			[] = "Disp Ornt";
const char pstrUsagePaletteReport				[] = "Pal Rpt";
const char pstrUsagePaletteDataSize				[] = "Pal Data Size";
const char pstrUsagePaletteDataOffset			[] = "Pal Data Off";
const char pstrUsagePaletteData					[] = "Pal Data";
const char pstrUsageBlitReport					[] = "Blit Rpt";
const char pstrUsageBlitRectangleX1				[] = "Blit Rect X1";
const char pstrUsageBlitRectangleY1				[] = "Blit Rect Y1";
const char pstrUsageBlitRectangleX2				[] = "Blit Rect X2";
const char pstrUsageBlitRectangleY2				[] = "Blit Rect Y2";
const char pstrUsageBlitData					[] = "Blit Data";
const char pstrUsageSoftButton					[] = "Soft Btn";
const char pstrUsageSoftButtonID				[] = "Soft Btn ID";
const char pstrUsageSoftButtonSide				[] = "Soft Btn Side";
const char pstrUsageSoftButtonOffset1			[] = "Soft Btn Off1";
const char pstrUsageSoftButtonOffset2			[] = "Soft Btn Off2";
const char pstrUsageSoftButtonReport			[] = "Soft Btn Rpt";

// Medical Instrument Page
const char pstrUsageMedicalUltrasound			[] = "Med Ultrasnd";
const char pstrUsageVCRAcquisition				[] = "VCR/Acq";
const char pstrUsageFreezeThaw					[] = "Freeze";
const char pstrUsageClipStore					[] = "Clip Store";
const char pstrUsageUpdate						[] = "Update";
const char pstrUsageNext						[] = "Next";
const char pstrUsageSave						[] = "Save";
const char pstrUsagePrint						[] = "Print";
const char pstrUsageMicrophoneEnable			[] = "Mic Enbl";
const char pstrUsageCine						[] = "Cine";
const char pstrUsageTransmitPower				[] = "Trans Pwr";
//const char pstrUsageVolume						[] = "Vol";
const char pstrUsageFocus						[] = "Focus";
const char pstrUsageDepth						[] = "Depth";
const char pstrUsageSoftStepPrimary				[] = "Soft Stp-Pri";
const char pstrUsageSoftStepSecondary			[] = "Soft Stp-Sec";
const char pstrUsageDepthGainCompensation		[] = "Dpth Gain Comp";
const char pstrUsageZoomSelect					[] = "Zoom Sel";
const char pstrUsageZoomAdjust					[] = "Zoom Adj";
const char pstrUsageSpectralDopplerModeSelect	[] = "Spec Dop Mode Sel";
const char pstrUsageSpectralDopplerModeAdjust	[] = "Spec Dop Mode Adj";
const char pstrUsageColorDopplerModeSelect		[] = "Color Dop Mode Sel";
const char pstrUsageColorDopplerModeAdjust		[] = "Color Dop Mode Adj";
const char pstrUsageMotionModeSelect			[] = "Motion Mode Sel";
const char pstrUsageMotionModeAdjust			[] = "Motion Mode Adj";
const char pstrUsage2DModeSelect				[] = "2D Mode Sel";
const char pstrUsage2DModeAdjust				[] = "2D Mode Adj";
const char pstrUsageSoftControlSelect			[] = "Soft Ctrl Sel";
const char pstrUsageSoftControlAdjust			[] = "Soft Ctrl Adj";

//extern const char *usagePageTitles0[15];
//const char *usagePageTitles1[];
//const char *genDesktopTitles0[];
//const char *genDesktopTitles1[];
//const char *genDesktopTitles2[];
//const char *genDesktopTitles3[];
//const char *genDesktopTitles4[];
//const char *simuTitles0[];
//const char *simuTitles1[];
//const char *simuTitles2[];
//const char *vrTitles0[];
//const char *vrTitles1[];
//const char *sportsCtrlTitles0[];
//const char *sportsCtrlTitles1[];
//const char *sportsCtrlTitles2[];
//const char *gameTitles0[];
//const char *gameTitles1[];
//const char *genDevCtrlTitles[];
//const char *ledTitles[];
//const char *telTitles0[];
//const char *telTitles1[];
//const char *telTitles2[];
//const char *telTitles3[];
//const char *telTitles4[];
//const char *telTitles5[];
//const char *consTitles0[];
//const char *consTitles1[];
//const char *consTitles2[];
//const char *consTitles3[];
//const char *consTitles4[];
//const char *consTitles5[];
//const char *consTitles6[];
//const char *consTitles7[];
//const char *consTitles8[];
//const char *consTitles9[];
//const char *consTitlesA[];
//const char *consTitlesB[];
//const char *consTitlesC[];
//const char *consTitlesD[];
//const char *consTitlesE[];
//const char *digitTitles0[];
//const char *digitTitles1[];
//const char *digitTitles2[];
//const char *aplphanumTitles0[];
//const char *aplphanumTitles1[];
//const char *aplphanumTitles2[];
//const char *medInstrTitles0[];
//const char *medInstrTitles1[];
//const char *medInstrTitles2[];
//const char *medInstrTitles3[];
//const char *medInstrTitles4[];

#endif /* HIDUSAGESTR_H_INCLUDED */
