#ifndef __SDK_VERSION_H__
#define __SDK_VERSION_H__

#define SDK_VERSION_MAJOR		0U
#define SDK_VERSION_MINOR		9U
#define SDK_VERSION_REVISION	3U
#define SDK_VERSION_INTERNAL    0U

#define SDK_VERSION   (SDK_VERSION_MAJOR << 16   | SDK_VERSION_MINOR << 8 | SDK_VERSION_REVISION)

#endif

