#!/usr/bin/env bash

obj_list=$(cat <<'END_LIST'
_atexit.o
clibrary_init.o
creat.o
isatty.o
lib_a-_Exit.o
lib_a-__adjust.o
lib_a-__atexit.o
lib_a-__call_atexit.o
lib_a-__dprintf.o
lib_a-__exp10.o
lib_a-__ten_mu.o
lib_a-a64l.o
# lib_a-abort.o
lib_a-abs.o
lib_a-argz_add.o
lib_a-argz_add_sep.o
lib_a-argz_append.o
lib_a-argz_count.o
lib_a-argz_create.o
lib_a-argz_create_sep.o
lib_a-argz_delete.o
lib_a-argz_extract.o
lib_a-argz_insert.o
lib_a-argz_next.o
lib_a-argz_replace.o
lib_a-argz_stringify.o
lib_a-asctime.o
lib_a-asctime_r.o
lib_a-asiprintf.o
lib_a-asniprintf.o
lib_a-asnprintf.o
lib_a-asprintf.o
lib_a-assert.o
lib_a-atexit.o
lib_a-atof.o
lib_a-atoff.o
lib_a-atoi.o
lib_a-atol.o
lib_a-atoll.o
lib_a-bcmp.o
lib_a-bcopy.o
lib_a-bsearch.o
lib_a-btowc.o
lib_a-buf_findstr.o
lib_a-bzero.o
# lib_a-calloc.o
# lib_a-callocr.o
lib_a-cfreer.o
lib_a-clearerr.o
lib_a-clock.o
lib_a-closer.o
lib_a-ctime.o
lib_a-ctime_r.o
lib_a-ctype_.o
lib_a-cxa_atexit.o
lib_a-cxa_finalize.o
lib_a-difftime.o
lib_a-diprintf.o
lib_a-div.o
lib_a-dprintf.o
lib_a-drand48.o
lib_a-dtoa.o
lib_a-dtoastub.o
lib_a-dummy.o
lib_a-ecvtbuf.o
lib_a-efgcvt.o
lib_a-environ.o
lib_a-envlock.o
lib_a-envz_add.o
lib_a-envz_entry.o
lib_a-envz_get.o
lib_a-envz_merge.o
lib_a-envz_remove.o
lib_a-envz_strip.o
lib_a-eprintf.o
lib_a-erand48.o
lib_a-errno.o
lib_a-execr.o
lib_a-exit.o
lib_a-fclose.o
lib_a-fcloseall.o
lib_a-fcntlr.o
lib_a-fdopen.o
lib_a-feof.o
lib_a-ferror.o
lib_a-fflush.o
lib_a-ffs.o
lib_a-fgetc.o
lib_a-fgetpos.o
lib_a-fgets.o
lib_a-fgetwc.o
lib_a-fgetws.o
lib_a-fileno.o
lib_a-findfp.o
lib_a-fini.o
lib_a-fiprintf.o
lib_a-fiscanf.o
lib_a-fix_grouping.o
lib_a-flags.o
lib_a-fmemopen.o
lib_a-fopen.o
lib_a-fopencookie.o
lib_a-fprintf.o
lib_a-fpurge.o
lib_a-fputc.o
lib_a-fputs.o
lib_a-fputwc.o
lib_a-fputws.o
lib_a-fread.o
# lib_a-freer.o
lib_a-freopen.o
lib_a-fscanf.o
lib_a-fseek.o
lib_a-fseeko.o
lib_a-fsetpos.o
lib_a-fstatr.o
lib_a-ftell.o
lib_a-ftello.o
lib_a-funopen.o
lib_a-fvwrite.o
lib_a-fwalk.o
lib_a-fwide.o
lib_a-fwprintf.o
lib_a-fwrite.o
lib_a-fwscanf.o
lib_a-gdtoa-gethex.o
lib_a-gdtoa-hexnan.o
lib_a-getc.o
lib_a-getc_u.o
lib_a-getchar.o
lib_a-getchar_u.o
lib_a-getdelim.o
lib_a-getenv.o
lib_a-getenv_r.o
lib_a-getline.o
lib_a-getopt.o
lib_a-getreent.o
lib_a-gets.o
lib_a-getsubopt.o
# lib_a-gettimeofdayr.o
lib_a-gettzinfo.o
lib_a-getw.o
lib_a-getwc.o
lib_a-getwchar.o
lib_a-gmtime.o
lib_a-gmtime_r.o
lib_a-hash.o
lib_a-hash_bigkey.o
lib_a-hash_buf.o
lib_a-hash_func.o
lib_a-hash_log2.o
lib_a-hash_page.o
lib_a-hcreate.o
lib_a-hcreate_r.o
lib_a-impure.o
lib_a-index.o
lib_a-init.o
lib_a-iprintf.o
lib_a-isalnum.o
lib_a-isalpha.o
lib_a-isascii.o
lib_a-isattyr.o
lib_a-isblank.o
lib_a-iscanf.o
lib_a-iscntrl.o
lib_a-isdigit.o
lib_a-islower.o
lib_a-isprint.o
lib_a-ispunct.o
lib_a-isspace.o
lib_a-isupper.o
lib_a-iswalnum.o
lib_a-iswalpha.o
lib_a-iswblank.o
lib_a-iswcntrl.o
lib_a-iswctype.o
lib_a-iswdigit.o
lib_a-iswgraph.o
lib_a-iswlower.o
lib_a-iswprint.o
lib_a-iswpunct.o
lib_a-iswspace.o
lib_a-iswupper.o
lib_a-iswxdigit.o
lib_a-isxdigit.o
lib_a-jp2uc.o
lib_a-jrand48.o
lib_a-l64a.o
lib_a-labs.o
lib_a-lcltime.o
lib_a-lcltime_r.o
lib_a-lcong48.o
lib_a-lctype.o
lib_a-ldiv.o
lib_a-ldpart.o
lib_a-ldtoa.o
lib_a-linkr.o
lib_a-llabs.o
lib_a-lldiv.o
lib_a-lmessages.o
lib_a-lmonetary.o
lib_a-lnumeric.o
lib_a-locale.o
lib_a-lrand48.o
lib_a-lseekr.o
lib_a-makebuf.o
lib_a-malign.o
lib_a-malignr.o
lib_a-mallinfor.o
# lib_a-malloc.o
# lib_a-mallocr.o
lib_a-malloptr.o
lib_a-mallstatsr.o
lib_a-mblen.o
lib_a-mblen_r.o
lib_a-mbrlen.o
lib_a-mbrtowc.o
lib_a-mbsinit.o
lib_a-mbsnrtowcs.o
lib_a-mbsrtowcs.o
lib_a-mbstowcs.o
lib_a-mbstowcs_r.o
lib_a-mbtowc.o
lib_a-mbtowc_r.o
lib_a-memccpy.o
lib_a-memchr.o
lib_a-memcmp.o
lib_a-memcpy.o
lib_a-memmem.o
lib_a-memmove.o
lib_a-mempcpy.o
lib_a-memrchr.o
lib_a-memset.o
lib_a-mkdirr.o
lib_a-mktemp.o
lib_a-mktime.o
lib_a-mktm_r.o
lib_a-mlock.o
lib_a-mprec.o
lib_a-mrand48.o
lib_a-msize.o
lib_a-msizer.o
lib_a-mstats.o
lib_a-mtrim.o
lib_a-nl_langinfo.o
lib_a-nrand48.o
lib_a-on_exit.o
lib_a-open_memstream.o
lib_a-openr.o
lib_a-perror.o
lib_a-printf.o
lib_a-psignal.o
# lib_a-putc.o
# lib_a-putc_u.o
# lib_a-putchar.o
# lib_a-putchar_u.o
lib_a-putenv.o
lib_a-putenv_r.o
# lib_a-puts.o
lib_a-putw.o
lib_a-putwc.o
lib_a-putwchar.o
lib_a-pvallocr.o
lib_a-qsort.o
lib_a-raise.o
lib_a-rand.o
lib_a-rand48.o
lib_a-rand_r.o
lib_a-readr.o
# lib_a-realloc.o
# lib_a-reallocf.o
# lib_a-reallocr.o
lib_a-reent.o
lib_a-refill.o
lib_a-remove.o
lib_a-rename.o
lib_a-renamer.o
lib_a-rewind.o
lib_a-rget.o
lib_a-rindex.o
lib_a-s_copysign.o
lib_a-s_finite.o
lib_a-s_fpclassify.o
lib_a-s_frexp.o
lib_a-s_infconst.o
lib_a-s_isinf.o
lib_a-s_isinfd.o
lib_a-s_isnan.o
lib_a-s_isnand.o
lib_a-s_ldexp.o
lib_a-s_modf.o
lib_a-s_nan.o
lib_a-s_scalbn.o
lib_a-sb_charsets.o
# lib_a-sbrkr.o
lib_a-scanf.o
lib_a-sccl.o
lib_a-seed48.o
lib_a-setbuf.o
lib_a-setbuffer.o
lib_a-setenv.o
lib_a-setenv_r.o
lib_a-setjmp.o
lib_a-setlinebuf.o
lib_a-setvbuf.o
lib_a-sf_copysign.o
lib_a-sf_finite.o
lib_a-sf_fpclassify.o
lib_a-sf_frexp.o
lib_a-sf_isinf.o
lib_a-sf_isinff.o
lib_a-sf_isnan.o
lib_a-sf_isnanf.o
lib_a-sf_ldexp.o
lib_a-sf_modf.o
lib_a-sf_nan.o
lib_a-sf_scalbn.o
lib_a-signal.o
lib_a-signalr.o
lib_a-signgam.o
lib_a-siprintf.o
lib_a-siscanf.o
lib_a-sniprintf.o
lib_a-snprintf.o
lib_a-sprintf.o
lib_a-srand48.o
lib_a-sscanf.o
lib_a-statr.o
lib_a-stdio.o
lib_a-stpcpy.o
lib_a-stpncpy.o
lib_a-strcasecmp.o
lib_a-strcasestr.o
lib_a-strcat.o
lib_a-strchr.o
lib_a-strchrnul.o
lib_a-strcmp.o
lib_a-strcoll.o
lib_a-strcpy.o
lib_a-strcspn.o
lib_a-strdup.o
lib_a-strdup_r.o
lib_a-strerror.o
lib_a-strerror_r.o
lib_a-strftime.o
lib_a-strlcat.o
lib_a-strlcpy.o
lib_a-strlen.o
lib_a-strlwr.o
lib_a-strncasecmp.o
lib_a-strncat.o
lib_a-strncmp.o
lib_a-strncpy.o
lib_a-strndup.o
lib_a-strndup_r.o
lib_a-strnlen.o
lib_a-strpbrk.o
lib_a-strptime.o
lib_a-strrchr.o
lib_a-strsep.o
lib_a-strsignal.o
lib_a-strspn.o
lib_a-strstr.o
lib_a-strtod.o
lib_a-strtok.o
lib_a-strtok_r.o
lib_a-strtol.o
lib_a-strtold.o
lib_a-strtoll.o
lib_a-strtoll_r.o
lib_a-strtoul.o
lib_a-strtoull.o
lib_a-strtoull_r.o
lib_a-strupr.o
lib_a-strxfrm.o
lib_a-svfiprintf.o
lib_a-svfiscanf.o
lib_a-svfiwprintf.o
lib_a-svfiwscanf.o
lib_a-svfprintf.o
lib_a-svfscanf.o
lib_a-svfwprintf.o
lib_a-svfwscanf.o
lib_a-swab.o
lib_a-swprintf.o
lib_a-swscanf.o
lib_a-sysclose.o
lib_a-sysexecve.o
lib_a-sysfcntl.o
lib_a-sysfork.o
lib_a-sysfstat.o
lib_a-sysgetpid.o
lib_a-sysgettod.o
lib_a-sysisatty.o
lib_a-syskill.o
lib_a-syslink.o
lib_a-syslseek.o
lib_a-sysopen.o
lib_a-sysread.o
lib_a-syssbrk.o
lib_a-sysstat.o
lib_a-system.o
lib_a-systimes.o
lib_a-sysunlink.o
lib_a-syswait.o
lib_a-syswrite.o
lib_a-tdelete.o
lib_a-tdestroy.o
lib_a-tfind.o
# lib_a-time.o
lib_a-timelocal.o
lib_a-timesr.o
lib_a-tmpfile.o
lib_a-tmpnam.o
lib_a-toascii.o
lib_a-tolower.o
lib_a-toupper.o
lib_a-towctrans.o
lib_a-towlower.o
lib_a-towupper.o
lib_a-tsearch.o
lib_a-twalk.o
lib_a-tzlock.o
lib_a-tzset.o
lib_a-tzset_r.o
lib_a-tzvars.o
lib_a-u_strerr.o
lib_a-unctrl.o
lib_a-ungetc.o
lib_a-ungetwc.o
lib_a-unlinkr.o
lib_a-valloc.o
lib_a-vallocr.o
lib_a-vasiprintf.o
lib_a-vasniprintf.o
lib_a-vasnprintf.o
lib_a-vasprintf.o
lib_a-vdiprintf.o
lib_a-vdprintf.o
lib_a-vfiprintf.o
lib_a-vfiscanf.o
lib_a-vfiwprintf.o
lib_a-vfiwscanf.o
lib_a-vfprintf.o
lib_a-vfscanf.o
lib_a-vfwprintf.o
lib_a-vfwscanf.o
lib_a-viprintf.o
lib_a-viscanf.o
lib_a-vprintf.o
lib_a-vscanf.o
lib_a-vsiprintf.o
lib_a-vsiscanf.o
lib_a-vsniprintf.o
lib_a-vsnprintf.o
lib_a-vsprintf.o
lib_a-vsscanf.o
lib_a-vswprintf.o
lib_a-vswscanf.o
lib_a-vwprintf.o
lib_a-vwscanf.o
lib_a-wbuf.o
lib_a-wcpcpy.o
lib_a-wcpncpy.o
lib_a-wcrtomb.o
lib_a-wcscasecmp.o
lib_a-wcscat.o
lib_a-wcschr.o
lib_a-wcscmp.o
lib_a-wcscoll.o
lib_a-wcscpy.o
lib_a-wcscspn.o
lib_a-wcsdup.o
lib_a-wcsftime.o
lib_a-wcslcat.o
lib_a-wcslcpy.o
lib_a-wcslen.o
lib_a-wcsncasecmp.o
lib_a-wcsncat.o
lib_a-wcsncmp.o
lib_a-wcsncpy.o
lib_a-wcsnlen.o
lib_a-wcsnrtombs.o
lib_a-wcspbrk.o
lib_a-wcsrchr.o
lib_a-wcsrtombs.o
lib_a-wcsspn.o
lib_a-wcsstr.o
lib_a-wcstod.o
lib_a-wcstok.o
lib_a-wcstol.o
lib_a-wcstold.o
lib_a-wcstoll.o
lib_a-wcstoll_r.o
lib_a-wcstombs.o
lib_a-wcstombs_r.o
lib_a-wcstoul.o
lib_a-wcstoull.o
lib_a-wcstoull_r.o
lib_a-wcswidth.o
lib_a-wcsxfrm.o
lib_a-wctob.o
lib_a-wctomb.o
lib_a-wctomb_r.o
lib_a-wctrans.o
lib_a-wctype.o
lib_a-wcwidth.o
lib_a-wmemchr.o
lib_a-wmemcmp.o
lib_a-wmemcpy.o
lib_a-wmemmove.o
lib_a-wmemset.o
lib_a-wprintf.o
lib_a-writer.o
lib_a-wscanf.o
lib_a-wsetup.o
lib_a-xpg_strerror_r.o
END_LIST
)
obj_list=$(echo "$obj_list" | sed '/^#/ d')

out_file=$PWD/libcmin.a
tmp_dir=libcmin_tmp
src_file=$PWD/libc_orig.a

rm -rf $out_file $tmp_dir
mkdir -p $tmp_dir
pushd $tmp_dir
xtensa-lx106-elf-ar x $src_file
for obj in $obj_list; do
    echo "Adding $obj"
    xtensa-lx106-elf-ar ru $out_file $obj
done
