/*
 * Automatically generated header file: don't edit
 */

#define HAVE_DOT_CONFIG 1
#undef CONFIG_PLATFORM_LINUX
#define CONFIG_PLATFORM_CYGWIN 1
#undef CONFIG_PLATFORM_SOLARIS
#undef CONFIG_PLATFORM_WIN32

/*
 * General Configuration
 */
#undef CONFIG_DEBUG
#undef CONFIG_VISUAL_STUDIO_6_0
#undef CONFIG_VISUAL_STUDIO_7_0
#undef CONFIG_VISUAL_STUDIO_8_0
#define CONFIG_VISUAL_STUDIO_6_0_BASE ""
#define CONFIG_VISUAL_STUDIO_7_0_BASE ""
#define CONFIG_VISUAL_STUDIO_8_0_BASE ""
#define CONFIG_EXTRA_CFLAGS_OPTIONS ""
#define CONFIG_EXTRA_LDFLAGS_OPTIONS ""

/*
 * SSL Library
 */
#undef CONFIG_SSL_SERVER_ONLY
#undef CONFIG_SSL_CERT_VERIFICATION
#undef CONFIG_SSL_ENABLE_CLIENT
#undef CONFIG_SSL_FULL_MODE
#define CONFIG_SSL_SKELETON_MODE 1
#undef CONFIG_SSL_PROT_LOW
#undef CONFIG_SSL_PROT_MEDIUM
#undef CONFIG_SSL_PROT_HIGH
#undef CONFIG_SSL_USE_DEFAULT_KEY
#define CONFIG_SSL_ENABLE_V23_HANDSHAKE 1
#undef CONFIG_SSL_HAS_PEM
#undef CONFIG_SSL_USE_PKCS12
#define CONFIG_SSL_EXPIRY_TIME 
#define CONFIG_X509_MAX_CA_CERTS 
#define CONFIG_SSL_MAX_CERTS 2
#define CONFIG_USE_DEV_URANDOM 1
#undef CONFIG_WIN32_USE_CRYPTO_LIB
#undef CONFIG_PERFORMANCE_TESTING
#undef CONFIG_SSL_TEST
#define CONFIG_AWHTTPD 1

/*
 * Awhttpd Configuration
 */
#undef CONFIG_HTTP_STATIC_BUILD
#define CONFIG_HTTP_HAS_SSL 1
#define CONFIG_HTTP_HTTPS_PORT 443
#undef CONFIG_STANDARD_AWHTTPD
#define CONFIG_HTTP_WEBROOT "www"
#define CONFIG_HTTP_PORT 80
#undef CONFIG_HTTP_USE_TIMEOUT
#define CONFIG_HTTP_TIMEOUT 
#define CONFIG_HTTP_INITIAL_SLOTS 10
#define CONFIG_HTTP_MAX_USERS 100
#define CONFIG_HTTP_HAS_CGI 1
#define CONFIG_HTTP_CGI_EXTENSION ".php"
#define CONFIG_HTTP_DIRECTORIES 1
#undef CONFIG_HTTP_PERM_CHECK
#undef CONFIG_HTTP_HAS_IPV6
#define CONFIG_HTTP_VERBOSE 1
#undef CONFIG_HTTP_IS_DAEMON

/*
 * Language Bindings
 */
#define CONFIG_BINDINGS 1
#define CONFIG_CSHARP_BINDINGS 1
#define CONFIG_VBNET_BINDINGS 1

/*
 * .Net Framework
 */
#define CONFIG_DOT_NET_FRAMEWORK_BASE "c:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727"
#define CONFIG_JAVA_BINDINGS 1

/*
 * Java Home
 */
#define CONFIG_JAVA_HOME "c:\\Program Files\\Java\\jdk1.5.0_06"
#undef CONFIG_PERL_BINDINGS
#define CONFIG_PERL_CORE ""
#define CONFIG_PERL_LIB ""

/*
 * Samples
 */
#define CONFIG_SAMPLES 1
#define CONFIG_C_SAMPLES 1
#define CONFIG_CSHARP_SAMPLES 1
#define CONFIG_VBNET_SAMPLES 1
#define CONFIG_JAVA_SAMPLES 1
#undef CONFIG_PERL_SAMPLES
#undef CONFIG_BIGINT_CLASSICAL
#undef CONFIG_BIGINT_MONTGOMERY
#undef CONFIG_BIGINT_BARRETT
#undef CONFIG_BIGINT_CRT
#undef CONFIG_BIGINT_KARATSUBA
#define MUL_KARATSUBA_THRESH 
#define SQU_KARATSUBA_THRESH 
#undef CONFIG_BIGINT_SLIDING_WINDOW
#undef CONFIG_BIGINT_SQUARE
#undef CONFIG_BIGINT_CHECK_ON
