/*
 * Automatically generated header file: don't edit
 */

#define HAVE_DOT_CONFIG 1
#undef CONFIG_PLATFORM_LINUX
#undef CONFIG_PLATFORM_CYGWIN
#undef CONFIG_PLATFORM_SOLARIS
#define CONFIG_PLATFORM_WIN32 1

/*
 * General Configuration
 */
#undef CONFIG_DEBUG

/*
 * Microsoft Compiler Options
 */
#undef CONFIG_VISUAL_STUDIO_6_0
#define CONFIG_VISUAL_STUDIO_7_0 1
#undef CONFIG_VISUAL_STUDIO_8_0
#define CONFIG_VISUAL_STUDIO_6_0_BASE ""
#define CONFIG_VISUAL_STUDIO_7_0_BASE "c:\\Program Files\\Microsoft Visual Studio .NET 2003"
#define CONFIG_VISUAL_STUDIO_8_0_BASE ""
#define CONFIG_EXTRA_CFLAGS_OPTIONS ""
#define CONFIG_EXTRA_LDFLAGS_OPTIONS ""

/*
 * SSL Library
 */
#undef CONFIG_SSL_SERVER_ONLY
#undef CONFIG_SSL_CERT_VERIFICATION
#undef CONFIG_SSL_ENABLE_CLIENT
#define CONFIG_SSL_FULL_MODE 1
#undef CONFIG_SSL_SKELETON_MODE
#undef CONFIG_SSL_PROT_LOW
#define CONFIG_SSL_PROT_MEDIUM 1
#undef CONFIG_SSL_PROT_HIGH
#define CONFIG_SSL_USE_DEFAULT_KEY 1
#define CONFIG_SSL_ENABLE_V23_HANDSHAKE 1
#define CONFIG_SSL_HAS_PEM 1
#define CONFIG_SSL_USE_PKCS12 1
#define CONFIG_SSL_EXPIRY_TIME 24
#define CONFIG_X509_MAX_CA_CERTS 4
#define CONFIG_SSL_MAX_CERTS 2
#undef CONFIG_USE_DEV_URANDOM
#define CONFIG_WIN32_USE_CRYPTO_LIB 1
#undef CONFIG_PERFORMANCE_TESTING
#define CONFIG_SSL_TEST 1
#define CONFIG_AWHTTPD 1

/*
 * Awhttpd Configuration
 */
#undef CONFIG_HTTP_STATIC_BUILD
#define CONFIG_HTTP_HAS_SSL 1
#define CONFIG_HTTP_HTTPS_PORT 443
#undef CONFIG_STANDARD_AWHTTPD
#define CONFIG_HTTP_WEBROOT "www"
#define CONFIG_HTTP_PORT 80
#undef CONFIG_HTTP_USE_TIMEOUT
#define CONFIG_HTTP_TIMEOUT 
#define CONFIG_HTTP_INITIAL_SLOTS 10
#define CONFIG_HTTP_MAX_USERS 100
#undef CONFIG_HTTP_HAS_CGI
#define CONFIG_HTTP_CGI_EXTENSION ""
#undef CONFIG_HTTP_DIRECTORIES
#undef CONFIG_HTTP_PERM_CHECK
#undef CONFIG_HTTP_HAS_IPV6
#define CONFIG_HTTP_VERBOSE 1
#undef CONFIG_HTTP_IS_DAEMON

/*
 * Language Bindings
 */
#define CONFIG_BINDINGS 1
#define CONFIG_CSHARP_BINDINGS 1
#define CONFIG_VBNET_BINDINGS 1

/*
 * .Net Framework
 */
#define CONFIG_DOT_NET_FRAMEWORK_BASE "c:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727"
#define CONFIG_JAVA_BINDINGS 1

/*
 * Java Home
 */
#define CONFIG_JAVA_HOME "c:\\Program Files\\Java\\jdk1.5.0_06"
#undef CONFIG_PERL_BINDINGS
#define CONFIG_PERL_CORE ""
#define CONFIG_PERL_LIB ""

/*
 * Samples
 */
#define CONFIG_SAMPLES 1
#define CONFIG_C_SAMPLES 1
#define CONFIG_CSHARP_SAMPLES 1
#define CONFIG_VBNET_SAMPLES 1
#define CONFIG_JAVA_SAMPLES 1
#undef CONFIG_PERL_SAMPLES

/*
 * BigInt Options
 */
#undef CONFIG_BIGINT_CLASSICAL
#undef CONFIG_BIGINT_MONTGOMERY
#define CONFIG_BIGINT_BARRETT 1
#define CONFIG_BIGINT_CRT 1
#undef CONFIG_BIGINT_KARATSUBA
#define MUL_KARATSUBA_THRESH 
#define SQU_KARATSUBA_THRESH 
#define CONFIG_BIGINT_SLIDING_WINDOW 1
#define CONFIG_BIGINT_SQUARE 1
#undef CONFIG_BIGINT_CHECK_ON
