#!/bin/sh

dir=$(cd ${0%/*}; pwd)
base=${0##*/}

csv=https://raw.githubusercontent.com/nayarsystems/posix_tz_db/master/zones.csv

input=/tmp/.tempfile-zones.csv
names=/tmp/.tempfile-names.txt
values=/tmp/.tempfile-values.txt

set -e

test -r $input && mv $input $input.old.$$
wget -O $input $csv || curl $csv > $input

sed -e 's/^[^,]*,//g' -e 's,^,PSTR(,g' -e 's,$,),g' < $input > $values
sed -e 's/^\([^,]*\),.*/#define TZ_\1/g' -e 's,["],,g' < $input | tr '/\-+' '_mp' > $names

(

cat << EOF

// autogenerated from $csv
// by script ../../tools/${base}
// $(date -u)
//
// This database is autogenerated from IANA timezone database
//    https://www.iana.org/time-zones
// and can be updated on demand in this repository
// or by yourself using the above script

#ifndef TZDB_H
#define TZDB_H

EOF

paste $names $values

cat << EOF

#endif // TZDB_H
EOF

) > /tmp/TZ.h.new

mv /tmp/TZ.h.new ${dir}/../cores/esp8266/TZ.h
